name: fruit_hub
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Fixed SDK constraint format

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1

flutter_launcher_icons:
  android: true  # Changed from "launcher_icon" to true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_launcher_icons: ^0.13.1  # Using a more stable version

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Uncomment to add assets
  assets:
    - assets/icon/icon.png

  # Fonts configuration remains commented
